name: hmm-kunitz
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - hmmer>=3.3.2
  - mmseqs2
  - cd-hit>=4.8.1
  - muscle>=5.0
  - biopython>=1.81
  - numpy>=1.24
  - pandas>=2.0
  - matplotlib>=3.7
  - pip
  - pip:
      - biopython>=1.81
